/*
** This table was originally generated by mt.c.
** These days we modify it manually.
*/

dd      Player_1_hard[] = {
        0x5c161fe4,     /* he_man */
        0x7b7921c3,     /* Steeple Chase (Video Gems) */
        0x02969f95,     /* Mission Survive */
        0xeab1d9d0,     /* Treasure Below */
        0x1f0bb3e0,     /* Eckhard's color test */
        0xe8e9b3c7,     /* Steeple Chase (Video Gems) NTSC (Thomas Jentzsch hack)*/
        0x7babc61b,     /* Mission Survive NTSC (Thomas Jentzsch hack)*/
        0x89a7cc41,     /* Treasure Below NTSC (Thomas Jentzsch hack)*/
        -1
};

dd      NTSC_colours[] = {
        0xfa07aa39,     /* pharhcrs (prevent auto-switch) */
        0x4f40a18e,     /* air_raid (too large) */
        -1
};

dd      PAL_colours[] = {
        0x361c9ac1,     /* Montezuma's Revenge PAL60 (Thomas Jentzsch hack) */
        0xf85c2f45,     /* Cosmic Commuter PAL60 (Thomas Jentzsch hack) */
        0x5260de42,     /* Cat Trax PAL60 (Thomas Jentzsch hack) */
        -1
};

dd	Kool[] = {
	0x6f721775,	/* Kool Aid Man.bin */
	0x75020f32,	/* Kool Aid Man-fix.bin */
	0xd5783d5c,	/* Kool Aid Man-sc.bin */
        0xb5b061a9,     /* Kool Aid Man (1982) (Mattel - Fabrizio Zavagi) (PAL).bin */
	-1
};

dd	Boxing[] = {
	0x19d692a0,	/* RealSports Boxing.bin */
	0xb43413a5,	/* RealSports Boxing_(eks).bin */
        0xe514f499,     /* Realsports Boxing (PAL) */
	-1
};

dd	Paddle_0[] = {
	0x56509fed,	/* Action Force - Action Man (Parker Bros) (PAL) [!].bin */
	0x52549f12,	/* Action Force - Action Man (Parker Bros).bin */
	0x8b232fbb,	/* Bachelor Party (Mystique).bin */
	0xd9c47532,	/* Bachelorette Party (Playaround).bin */
	0xf89d2e22,	/* Backgammon (1978) (Atari) (PAL) [!].bin */
	0xe24e8139,	/* Backgammon (1978) (Atari).bin */
	0xaf28b265,	/* Beat 'Em and Eat 'Em (Mystique) [!].bin */
	0x970a7c6c,	/* Blackjack (1977) (Atari) [o].bin */
	0xd3fa0c42,	/* Blackjack (1977) (Atari).bin */
	0x0e18a4ca,	/* Blackjack (32 in 1) (PAL).bin */
	0x01c90f83,	/* Breakout - Breakaway IV (Atari) (1978) [o1].bin */
	0x0f799975,	/* Breakout - Breakaway IV (Atari) (1978) [o2].bin */
	0xf89729af,	/* Breakout - Breakaway IV (Atari) (1978) [t].bin */
	0x74946443,	/* Breakout - Breakaway IV (Atari) (1978).bin */
	0x82a03bb7,	/* Breakout - Breakaway IV (Atari) (PAL) [!].bin */
	0xd8c2d1d3,	/* Bugs.bin */
	0xbbf361b2,	/* Casino - Poker Plus (1978).bin */
	0xed6c5505,	/* Casino (Atari) (PAL) [!].bin */
	0x8cf289e1,	/* Circus Atari (1978) (Atari) (Paddles).bin */
	0x767c52c3,	/* Circus Atari (1978) (Atari) (PAL) [!].bin */
	0xd2d31b9f,	/* Eggomania.bin */
	0x8fc7a660,	/* Encounter at L5.bin */
	0xb1ac01ae,	/* G.I. Joe - Cobra Strike (Parker Bros) [!].bin */
	0x66202e85,	/* Guardian.bin */
	0x492ed335,	/* Kaboom! (Activision) (PAL) [!].bin */
	0xe0e215ef,	/* Kaboom! (CCE).bin */
	0xe65930a1,	/* Kaboom! [o1].bin */
	0xbe6d413b,	/* Kaboom! [o2].bin */
	0xf2d1b43c,	/* Kaboom!.bin */
	0x41167e30,	/* Mondo Pong V1 (Piero Cavina) (PD).bin */
	0x451f45dd,	/* Mondo Pong.bin */
	0xa550e765,	/* Music Machine.bin */
	0xf438f25d,	/* Night Driver (1978) [o].bin */
	0xf2ab3c3b,	/* Night Driver (1978).bin */
	0xa1af9971,	/* Philly Flasher.bin */
	0x17e3509b,	/* Picnic.bin */
	0x1eddbbff,	/* Piece o' Cake.bin */
	0x22965081,	/* Secret Agent (Prototype).bin */
	0x922a0836,	/* Solar Storm.bin */
        0xc4e4ff1a,     /* Solar Storm (1983) (Imagic) (PAL) [!].bin */
	0xa914ed81,	/* Starpath - Fireball (PAL).bin */
	0x0ef334f7,	/* Starpath - Fireball (Preview) (PAL).bin */
	0x5192bfbf,	/* Starpath - Fireball (Preview).bin */
	0x136959ff,	/* Starpath - Fireball [a].bin */
	0x19fc874c,	/* Starpath - Fireball.bin */
	0x7f2bee1e,	/* Starpath - Party Mix (1 of 3) (PAL).bin */
	0xf4b12a3e,	/* Starpath - Party Mix (1 of 3).bin */
	0xe3028001,	/* Starpath - Party Mix (2 of 3) (PAL).bin */
	0x1bdbeff7,	/* Starpath - Party Mix (2 of 3).bin */
	0xdc5341c3,	/* Starpath - Party Mix (3 of 3) (PAL).bin */
	0x5ef85036,	/* Starpath - Party Mix (3 of 3).bin */
	0x35d3a20c,	/* Starpath - Party Mix (Preview) (PAL).bin */
	0xc0d6f4e8,	/* Starpath - Party Mix (Preview).bin */
	0x96c728ee,	/* Starpath - Party Mix.bin */
	0xe707a714,	/* Starpath - Sweat! - The Decathalon Game (1 of 2).bin */
	0x6d05e1cb,	/* Starpath - Sweat! - The Decathalon Game (2 of 2).bin */
	0x7ef1a47d,	/* Starpath - Sweat! - The Decathalon Game.bin */
	0xa6c4a5fd,	/* Steeplechase (Sears) [o].bin */
	0x0d6f4f89,	/* Steeplechase (Sears).bin */
	0x2b520955,	/* Super Breakout (1978).bin */
	0x31b91b55,	/* Super Breakout (Atari) (PAL) [!].bin */
	0x9c13d012,	/* Super Breakout (Atari) (PAL) [a].bin */
	0x81bbf60b,	/* Warlords (Atari) (PAL) [!].bin */
	0x65ef1ff1,	/* Warlords.bin */
	0x75a39600,	/* Warplock.bin */
	0x235e3b9c,	/* Breakout_(eks).bin */
	0x545dba81,	/* Night Driver_(eks).bin */
	0x450650d5,	/* Super Breakout_(eks).bin */
        0x9ded5a9c,     /* Blackjack (PAL) */
        0x7d39ac38,     /* SCSIcide release 1 */
        0x1ccac7fd,     /* SCSIcide release 2 */
        0x04839db5,     /* SCSIcide release 3 */
	-1
};

dd	Paddle_1[] = {
	0x3654b4df,	/* Canyon Bomber (1978) [o].bin */
	0x4d5d81e5,	/* Canyon Bomber (1978).bin */
	0x3e7ece9b,	/* Demons to Diamonds (Atari) (PAL) [!].bin */
	0x69cd3201,	/* Demons to Diamonds (CCE).bin */
	0x7e18d535,	/* Demons to Diamonds.bin */
	0x4103ddc3,	/* Star Wars - Jedi Arena (Parker Bros) (PAL) [!].bin */
	0xa4809298,	/* Star Wars - Jedi Arena (Parker Bros).bin */
	0x3b5d801a,	/* Street Racer - Speedway II (1978) (Atari) [o].bin */
	0x131e9db3,	/* Street Racer - Speedway II (1978) (Atari).bin */
	0xd966099e,	/* Video Olympics - Pong Sports (1977) (Atari) [o].bin */
	0xeb148808,	/* Video Olympics - Pong Sports (1977) (Atari).bin */
	0x878d33f5,	/* Video Olympics (Atari) (PAL) [!].bin */
	0x88e40492,	/* Street Racer_(eks).bin */
	-1
};

dd	Paddle_3[] = {
	0x8c2f6264,	/* Tac Scan (Sega).bin */
	-1
};

dd	MPdir_1[] = {
	0x8b232fbb,	/* Bachelor Party (Mystique).bin */
	0xd9c47532,	/* Bachelorette Party (Playaround).bin */
	0x970a7c6c,	/* Blackjack (1977) (Atari) [o].bin */
	0xd3fa0c42,	/* Blackjack (1977) (Atari).bin */
	0x0e18a4ca,	/* Blackjack (32 in 1) (PAL).bin */
	0xbbf361b2,	/* Casino - Poker Plus (1978).bin */
	0xed6c5505,	/* Casino (Atari) (PAL) [!].bin */
	0xdc5341c3,	/* Starpath - Party Mix (3 of 3) (PAL).bin */
	0x5ef85036,	/* Starpath - Party Mix (3 of 3).bin */
	0xa6c4a5fd,	/* Steeplechase (Sears) [o].bin */
	0x0d6f4f89,	/* Steeplechase (Sears).bin */
        0x9ded5a9c,     /* Blackjack (PAL) */
	-1
};

dd	MPdir_2[] = {
	0x095a655f,	/* Marble Craze NTSC */
	0x96a0b1f9,	/* Marble Craze PAL */
	-1
};

dd	MPdir_3[] = {
	0xf89d2e22,	/* Backgammon (1978) (Atari) (PAL) [!].bin */
	0xe24e8139,	/* Backgammon (1978) (Atari).bin */
	0x3654b4df,	/* Canyon Bomber (1978) [o].bin */
	0x4d5d81e5,	/* Canyon Bomber (1978).bin */
	0x41167e30,	/* Mondo Pong V1 (Piero Cavina) (PD).bin */
	0x451f45dd,	/* Mondo Pong.bin */
	0xe707a714,	/* Starpath - Sweat! - The Decathalon Game (1 of 2).bin */
	0xd966099e,	/* Video Olympics - Pong Sports (1977) (Atari) [o].bin */
	0xeb148808,	/* Video Olympics - Pong Sports (1977) (Atari).bin */
	0x878d33f5,	/* Video Olympics (Atari) (PAL) [!].bin */
        0x7d39ac38,     /* SCSIcide release 1 */
        0x1ccac7fd,     /* SCSIcide release 2 */
        0x04839db5,     /* SCSIcide release 3 */
	-1
};

dd	joy_rev[] = {
	0x7b4eb49c,	/* Pick 'n Pile.bin */
	0xe2134ede,	/* Raiders of the Lost Ark (Atari) (PAL) [!].bin */
	0x0eb247a3,	/* Raiders of the Lost Ark (Atari).bin */
	0xbcb42d2b,	/* Traffic.bin */
	-1
};

dd	keypad_3[] = {
	0x569bcd98,	/* Alpha Beam with Ernie (Atari) (PAL) [!].bin */
	0x9a1a860b,	/* Alpha Beam with Ernie (Atari).bin */
	0x98efb758,	/* Basic Programming (1978) (Atari).bin */
	0x30f80509,	/* Big Bird's Egg Catch (Atari) (PAL) [!].bin */
	0xf57c88c7,	/* Big Bird's Egg Catch (Atari).bin */
	0xa13e9a41,	/* Brain Games (Atari) (PAL) [!].bin */
	0xa070e611,	/* Brain Games (Atari) [o].bin */
	0x27ff9feb,	/* Brain Games (Atari).bin */
	0x12fc4f0e,	/* Code Breaker (1978) [o].bin */
	0x33eab939,	/* Code Breaker (1978).bin */
	0x9a997a6a,	/* Code Breaker (Atari) (PAL) [!].bin */
	0xad9d0c8b,	/* Cookie Monster Munch (Atari) (PAL) [!].bin */
	0xdcf49717,	/* Cookie Monster Munch (Prototype) (PAL).bin */
	0x3d4e3a13,	/* Game of Concentration [o].bin */
	0xbb09444c,	/* Game of Concentration.bin */
	0x97a27db8,	/* Grover's Music Maker (Prototype) (PAL).bin */
	0x34ae2945,	/* Magicard (CommaVid).bin */
	0xf1a47d0e,	/* Oscar's Trash Race (Atari) (PAL) [!].bin */
	0x0f76fc86,	/* Oscar's Trash Race (Prototype) (PAL).bin */
	0xc1e0f57f,	/* Basic Programming_(eks).bin */
	0x751a433a,	/* Game of Concentration_(eks).bin */
	0x9afa761f,	/* Magicard (Life).bin */
        0xf777a07d,     /* Holey Moley (Prototype) */
        0xc3e91b95,     /* Peek-A-Boo (Prototype) */
        0x7c384d26,     /* Magicard (example program 1) */
        0x30c54700,     /* Magicard (example program 2) */
        0x5e7a5ac4,     /* Magicard (example program 3) */
        0x27e4a094,     /* Magicard (example program 4) */
        0xf1a0a2bd,     /* Paul Slocum's Synthcart */
	-1
};

dd	keypad_2[] = {
	0x6cd15ce4,	/* Star Raiders (Atari) (PAL) [!].bin */
	0x80c51507,	/* Star Raiders (Atari).bin */
	0x6cd14bf3,	/* Star Raiders_(eks).bin */
	-1
};

dd      driving_con_2[] = {
        0x1a5a782c,     /* Asteroids DC+ (Thomas Jentzsch hack) */
	-1
};

dd      driving_con_3[] = {
	0x8a5cdc67,	/* Indy 500 (1977) (Atari) [h].bin */
	0x40f4dd41,	/* Indy 500 (1977) [o].bin */
	0xf6347068,	/* Indy 500 (1977).bin */
	0x3038f1e5,	/* Indy 500 (Atari) (PAL) [!].bin */
        0xb7beb2bb,     /* Indy 500 (1978) (Atari) (PAL) [p1][o1][!].bin */
        0x5b9f7df7,     /* Sprint Master DC (Thomas Jentzsch hack) */
	-1
};

dd	BS_1[] = {
	0x34ae2945,	/* Magicard (CommaVid).bin */
	0x30eb4f7a,	/* Video Life (4K).BIN */
	0x9afa761f,	/* Magicard (Life).bin */
	0x266bd1b6,	/* Video Life (CommaVid).bin */
        0xa0899305,     /* Video Life (alternative 2K) */
        0xfbb4ac5f,     /* Video Life (4K) from DP */
        0x7c384d26,     /* Magicard (example program 1) */
        0x30c54700,     /* Magicard (example program 2) */
        0x5e7a5ac4,     /* Magicard (example program 3) */
        0x27e4a094,     /* Magicard (example program 4) */
	-1
};

dd	BS_3[] = {
	0x2843d776,	/* Frogger II - Threedeep!.bin */
	0x690ada72,	/* Gyruss [b].bin */
	0x525ee7e9,	/* Gyruss.bin */
	0x95da4070,	/* James Bond 007 [b].bin */
	0x3216c1bb,	/* James Bond 007.bin */
	0xae4114d8,	/* Montezuma's Revenge.bin */
	0x00e44527,	/* Mr. Do!'s Castle.bin */
	0xf723b8a6,	/* Popeye.bin */
	0xe44c244e,	/* Q-bert's Qubes [a].bin */
	0xb8f2dca6,	/* Q-bert's Qubes.bin */
	0xe77f6742,	/* Star Wars - Death Star Battle (Parker Bros).bin */
	0xce09fcd4,	/* Star Wars - The Arcade Game (Parker Bros).bin */
	0xdd85f0e7,	/* Super Cobra [b].bin */
	0x8d372730,	/* Super Cobra.bin */
	0xd9088807,	/* Tooth Protectors (DSD-Camelot).bin */
	0x7eed7362,	/* Tutankham.bin */
	0xc87fc312,	/* Popeye_(eks).bin */
	0xef3ec01e,	/* Super Cobra_(eks).bin */
	0x84a101d4,	/* Star Wars - Death Star Battle_(eks).bin */
	0x2fc06cb0,	/* Tutankham_(eks).bin */
	0xab50bf11,	/* Star Wars - The Arcade Game (proto).BIN */
        0x549a1b6b,     /* Star Wars - The Arcade Game (PAL) */
        0x36910e4d,     /* Frogger II - Threedeep! (PAL) */
        0xb8bb2361,     /* Gyruss (PAL) */
        0xd3669372,     /* Star Wars: Ewok Adventure (proto) */
        0x6400d110,     /* Lord of the Rings: Journey to Rivendell (proto) */
        0x70db5cca,     /* Ewok Adventure NTSC (Thomas Jentzsch hack) */
        0x361c9ac1,     /* Montezuma's Revenge PAL60 (Thomas Jentzsch hack) */
        -1
};

dd	BS_4[] = {
	0x584f6777,	/* Espial [b].bin */
	0x8d70fa42,	/* Espial.bin */
        0x8a7317da,     /* Espial (1983) (Tigervision) [b2].bin */
	0x8beb03d4,	/* Miner 2049er [b1].bin */
	0x33f2856f,	/* Miner 2049er [b2].bin */
	0xf859122e,	/* Miner 2049er Vol. 2 [b1].bin */
	0x281a1ca1,	/* Miner 2049er Vol. 2 [b2].bin */
	0x350c63ba,	/* Miner 2049er Vol. 2.bin */
	0x728b941c,	/* Miner 2049er.bin */
	0x13bf2da3,	/* Polaris [b].bin */
	0x7ce5312e,	/* Polaris.bin */
	0x40706361,	/* River Patrol (Tigervision).bin */
	0x2c34898f,	/* Springer.bin */
        0x09a71583,     /* Miner 2049er PAL */
        0xd5645294,     /* Miner Volume 2 NTSC */
        0x3310b79e,     /* Polaris NTSC ? */
        0x52630ec9,     /* Polaris NTSC (Thomas Jentzsch hack) */
	-1
};

dd	BS_5[] = {
	0x7d23e780,	/* Decathlon.bin */
	0xa51c0236,	/* Robot Tank.bin */
        0xd8ecf576,     /* Decathlon (PAL) */
        0x0e8757b0,     /* Robot Tank (PAL) */
        0x94e8df6b,     /* Space Shuttle (PAL) */
        0xf3a4363c,     /* Thwocker prototype */
        0x0a4d0768,     /* Robot Tank TC (Thomas Jentzsch hack) */
        0xc343187b,     /* Space Shuttle (NTSC) */
	-1
};

dd	BS_9[] = {
	0x6a31beac,	/* Private Eye (CCE).bin */
	0x3fa749c0,	/* Private Eye [b].bin */
	0x33242242,	/* Private Eye.bin */
        0x2956b245,     /* Snow White (proto) */
	-1
};

dd	BS_6[] = {
	0xa972c32b,	/* Dig Dug.bin */
	0x66cdb94b,	/* Off the Wall [o].bin */
	0xbd75d92b,	/* Off the Wall.bin */
	-1
};

dd	BS_7[] = {
	0x8eed6b02,	/* Bump n Jump [b].bin */
	0xd523e776,	/* Bump n Jump.bin */
        0x9395c6b7,     /* Breaking News (Ric Pryor).bin */
	0x24c35820,	/* Burgertime.bin */
	0x5c161fe4,	/* Masters of the Universe - The Power of He-Man.bin */
	-1
};

/*
dd	BS_8[] = {
        0xbe1047cf,      Fatal Run (PAL).bin 
	-1
};
*/

dd	BS_11[] = {
	0x2e76744c,	/* beu11.bin */
	-1
};
	
dd      BS_12[] = {
        0x39c892c7,     /* Pleiades prototype */
        0xbc5527e7,     /* Pleiades prototype (fixed) */
        0x2c19c728,     /* Funky Fish prototype */
        -1              /* UA Ltd. prototypes go here */
};


dd	Phosphorescent[] = {
  0xa7890826,  /* alien.bin */
  0xacdb6441,  /* astroidc.bin */
  0xd6baa6cf,  /* astroids.bin */
  0x8b232fbb,  /* bachelor.bin */
  0xd9c47532,  /* bachlrtt.bin */
  0x98efb758,  /* basicprg.bin */
  0x2e76744c,  /* beu11.bin */
  0x16b1a362,  /* blueprnt.bin */
  0x2c636eb6,  /* boing.bin */
  0x5474d585,  /* buckrog.bin */
  0x75bd9195,  /* cathouse.bin */
  0x4323a078,  /* catmouse.bin */
  0x1cb28465,  /* chinasyn.bin */
  0xa01ebff4,  /* compumat.bin */
  0x8fa212f4,  /* cosmcrep.bin */
  0xbf933de2,  /* cosmswrm.bin */
  0xd7036918,  /* crimlpur.bin */
  0x00ba2d68,  /* darkcham.bin */
  0x1d12e8c1,  /* demohrby.bin */
  0xe77f6742,  /* dethstar.bin */
  0x15d8e02b,  /* dethtrap.bin */
  0xaebfd482,  /* dicepuzl.bin */
  0x57f730ee,  /* dishastr.bin */
  0xb87a10b7,  /* dm.bin */
  0x00e44527,  /* docastle.bin */
  0x7117e8a9,  /* drgndfnd.bin */
  0xd36c9159,  /* entombed.bin */
  0x05a357e7,  /* fathom.bin */
  0xe8b1225f,  /* firespin.bin */
  0x9d63d054,  /* forest.bin */
  0x36910e4d,  /* frogger2.bin */
  0x1ee7036e,  /* ghost2.bin */
  0xa0794137,  /* gigolo.bin */
  0x2bc25098,  /* gorf.bin */
  0xb8bb2361,  /* gyruss.bin */
  0xc39c7a29,  /* infiltrt.bin */
  0xc4be9818,  /* iwantmom.bin */
  0xde6d008e,  /* joust.bin */
  0x714a692b,  /* knightwn.bin */
  0xc09801fb,  /* ladywdng.bin */
  0x67b79cd2,  /* malagai.bin */
  0x421d090e,  /* minemnos.bin */
  0x350c63ba,  /* minrvol2.bin */
  0x80f5e00e,  /* misn3000.bin */
  0xf48b6b4c,  /* misslcmd.bin */
  0x393372e5,  /* motor.bin */
  0x405464ee,  /* mousetrp.bin */
  0x596160d3,  /* mrdo.bin */
  0x80f09601,  /* mtnking.bin */
  0xf2ab3c3b,  /* nightdrv.bin */
  0x27e43843,  /* opensesm.bin */
  0xfa07aa39,  /* pharhcrs.bin */
  0x86bc321d,  /* phasor.bin */
  0x91405d9c,  /* phasrpal.bin */
  0xf723b8a6,  /* popeye.bin */
  0xa36f7aa4,  /* qb217.bin */
  0x85bc70de,  /* racquetb.bin */
  0x2aace942,  /* robofght.bin */
  0x5a21e1cb,  /* roboto.bin */
  0x62171047,  /* roomdoom.bin */
  0x55da122d,  /* rs_baseb.bin */
  0x5b171752,  /* rs_footb.bin */
  0x231e70a6,  /* spcrobot.bin */
  0x39a5f247,  /* startrek.bin */
  0x57b51249,  /* steltrak.bin */
  0x14f2ef2a,  /* sudmopal.bin */
  0xce9cd420,  /* suicdemo.bin */
  0x9fd23f79,  /* suicdpal.bin */
  0x51d72cee,  /* suicid23.bin */
  0x9b4f27df,  /* suicide.bin */
  0xce09fcd4,  /* swarcade.bin */
  0x8c2f6264,  /* tacscan.bin */
  0xaedb3c29,  /* tetris26.bin */
  0x34132e52,  /* thundgrd.bin */
  0xd9088807,  /* toothpro.bin */
  0x9a46f393,  /* tricksht.bin */
  0x29c93a2c,  /* venture.bin */
  0x7b7921c3,  /* vg_steep.bin */
  0x02969f95,  /* vg_survi.bin */
  0x30eb4f7a,  /* vidlife4.bin */
  0x266bd1b6,  /* vidlife.bin */
  0xa0899305,  /* vidlifex.bin */
  0x646d7ecb,  /* wallball.bin */
  0x75a39600,  /* warplock.bin */
  0x8973f4af,  /* xevious.bin */
  0x897a5109,  /* yars.bin */
  0x29ddddc1,  /* z26-2.bin */
  0x19a6dd6a,  /* z26.bin */
  0x7bb15e70,  /* asteroid.bin (PAL games) */
  0xc1e0f57f,  /* basicprg.bin */
  0x2d9fa0e8,  /* blueprnt.bin */
  0x17b9b5bd,  /* chinasyn.bin */
  0x835db16f,  /* csmswarm.bin */
  0x01088310,  /* darkcham.bin */
  0x1ef047f1,  /* gorf.bin */
  0x525ee7e9,  /* gyruss.bin */
  0xb7ae061d,  /* joust.bin */
  0xf45b259c,  /* langfing.bin */
  0x80f5e00e,  /* misn3000.bin */
  0xa3ff7697,  /* misscomm.bin */
  0x545dba81,  /* nghtdrvr.bin */
  0xc87fc312,  /* popeye.bin */
  0x2aace942,  /* raumrobo.bin */
  0x79b7409f,  /* schutzdr.bin */
  0x4c59992d,  /* trikshot.bin */
  0x0e2fa6d9,  /* yarsrvng.bin */
  0x5f818633,  /* Asteroids 2.bin */
  0x76814d29,  /* Asteroids (Atari) (PAL) [!].bin */
  0xb7ae110a,  /* Atari - CX-26091 - Joust (PAL).bin */
  0xe9c904ad,  /* Atari - CX-26145 - Venture (PAL).bin */
  0x5c44872b,  /* Big Move This Demo 2 (PD).bin */
  0x2c5a14da,  /* CBS Electronics - Mouse Trap (PAL).bin */
  0xd3fe7a71,  /* CBS Electronics - Venture (PAL).bin */
  0x4d2d3b41,  /* CommaVid - Room of Doom (PAL - not sure).bin */
  0xfec87e0d,  /* Confrontation.bin */
  0x3207fed6,  /* Cosmic Swarm (4k).bin */
  0xd3b1a2d4,  /* Cosmic Swarm (32 in 1) (PAL).bin */
  0x830bb210,  /* Dark Mage (Supercharger) (PD).bin */
  0xb214ab6b,  /* Dark_Mage_(4K).bin */
  0x2843d776,  /* Frogger II - Threedeep!.bin */
  0x9c5c953c,  /* Imagic - Trick Shot (PAL).bin */
  0x3216c1bb,  /* James Bond 007.bin */
  0x568a18cb,  /* John K Harvey's Equalizer (NTSC) (PD).bin */
  0x0a0c9d67,  /* John K Harvey's Equalizer (PAL) (PD).bin */
  0x3d77201b,  /* Journey Escape.bin */
  0x99421574,  /* Mark's Sound Demo.BIN */
  0xee63a2ad,  /* Missle Command (graphics hack).bin */
  0xf438f25d,  /* Night Driver (4k).bin */
  0x4b2fb9aa,  /* Scroller Demo (Bob Colbert) (PD).bin */
  0x4c5736a9,  /* Spectravideo - Tape Worm (PAL).bin */
  0xa3ef6b2a,  /* Starpath - Phaser Patrol [a].bin */
  0xd7298b0b,  /* Starpath - Suicide Mission [a].bin */
  0x8d873cc8,  /* Starsoft (Without S.S. Initiales on the Back Side) Billard (PAL).bin */
  0x9fed8dab,  /* Starsoft (Without S.S. Initiales on the Back Side) Die Springteufel (PAL).bin */
  0x9cdc81b6,  /* Stell-A-Sketch.bin */
  0xd7818beb,  /* Super Futebol (CCE).bin */
  0xc6b33c95,  /* TechnoVision - Pharaoh's Curse (PAL).bin */
  0x63d00489,  /* Teddy Apple.bin */
  0xc29e2e3a,  /* Tetris 2600 (Colin Hughes) [o].bin */
  0xe03a1d85,  /* Universal Chaos (PAL).bin */
  0x56c0f7f1,  /* Xevious (CCE).bin */
  0x1ed37ebd,  /* Yar's Revenge (1).bin */
  0x90ecad98,  /* Alien (CCE).bin */
  0xf58ddf00,  /* Apples and Dolls (CCE).bin */
  0xf5f8ffff,  /* Dancing Plate (PAL).bin */
  0xa93dc2c1,  /* Green and Yellow Number 1 Demo 2 (PD).bin */
  0x1e54c27f,  /* Green and Yellow Number 1 Demo (PD).bin */
  0x93f996cd,  /* John K Harvey's Equalizer (NTSC) (PD) [a].bin */
  0x5c161fe4,  /* Masters of the Universe - The Power of He-Man.bin */
  0xcc486b15,  /* Moving Maze Demo (PD).bin */
  0x07da7621,  /* ZZZ_UNK_A2600_rom_039.bin */
  0x5e788eef,  /* ZZZ_UNK_A2600_rom_061.bin */
  0x93f434be,  /* ZZZ_UNK_A2600_rom_072.bin */
  0x98f16ea6,  /* ZZZ_UNK_A2600_rom_073.bin */
  0x37cb87d8,  /* Blueprint (CBS Electronics) (PAL) [!].bin */
  0x5c74d64e,  /* Fathom (1983) (Imagic) (PAL) [!].bin */
  0x8da45a53,  /* Hili Ball (Starsoft) (PAL) [!].bin */
  0x4f40a18e,  /* Air Raid.bin */
  0x80eb88e9,  /* Aster Hawk (Charles Morgan).bin */
  0x0445fd44,  /* Asteroids (Scott Stilphen) (Hack).bin */
  0x1a5a782c,  /* Asteroids DC+ (Thomas Jentzsch).bin */
  0xaa3812af,  /* Attack Of The Mutant Space Urchins (Barry Laws Jr.).bin */
  0xe5a25575,  /* Boing! (1983) (First Star Software) (PAL) [!].bin */
  0x5260de42,  /* Cat Trax (Thomas Jentzsch) (PAL) (Video Format Conversion).bin */
  0x0e5bea23,  /* Cosmic Creeps (1982) (Telesys) (PAL) [p1][!].bin */
  0xa3b903fd,  /* Cosmic Swarm (1982) (CommaVid) (PAL) [p1][o1][!].bin */
  0x6d811131,  /* Dancing Plate (PAL) [p1][!].bin */
  0xd22f87fb,  /* Demolition Herby (1982) (Telesys) (PAL) [p1][!].bin */
  0xb5a677d1,  /* Dice Puzzle (Panda) (PAL) [p1][!].bin */
  0xbfc1da38,  /* Dragon Defender (Thomas Jentzsch) (Video Format Conversion).bin */
  0x6570d0eb,  /* Ghostbusters II (Salu, Thomas Jentzsch).bin */
  0x117fb266,  /* Ghostbusters II (Version 2).bin */
  0x9ad328b9,  /* Hili Ball (Starsoft) (PAL) [p1][!].bin */
  0x49176010,  /* Lord of the Rings-Fellowship of the Ring (Hack) (Improved Engine).bin */
  0xe52bdc22,  /* Lord of the Rings-Fellowship of the Ring (Hack).bin */
  0x9a1d148e,  /* Mines of Minos (CommaVid) (PAL) [!].bin */
  0x4736543c,  /* Mines of Minos (CommaVid) (PAL) [p1][!].bin */
  0xe4062d87,  /* Missile Command (Amiga Mouse) (Thomas Jentzsch) (PAL).bin */
  0x8590dabb,  /* Missile Command (Amiga Mouse) (Thomas Jentzsch).bin */
  0xe69da7c3,  /* Missile Command (Atari) (PAL) [p1][!].bin */
  0x90215889,  /* Missile Command (CX-22 Trackball) (Thomas Jentzsch) (PAL).bin */
  0x8f7e1223,  /* Missile Command (CX-22 Trackball) (Thomas Jentzsch).bin */
  0x094ed116,  /* Missile Command (CX-80 Trackball) (Thomas Jentzsch) (PAL).bin */
  0x16119bbc,  /* Missile Command (CX-80 Trackball) (Thomas Jentzsch).bin */
  0x9a650e9c,  /* Misterious Thief, A (CCE).bin */
  0xcb966e55,  /* Moonsweeper (1983) (Imagic) (PAL) [!].bin */
  0xd865a8dd,  /* Moonsweeper (1983) (Imagic).bin */
  0xa7ce1800,  /* Mr. Do! (1983) (CBS Electronics) (PAL) [!].bin */
  0x1bcbba9e,  /* Pharaoh's Curse (TechnoVision) (PAL) [p1][!].bin */
  0xb087d2b6,  /* Pharaoh's Curse (TechnoVision, Thomas Jentzsch).bin */
  0x7b4eb49c,  /* Pick 'n Pile (1990) (Salu) (PAL) [!].bin */
  0xdc3c5a3f,  /* Qb (2.06) (NTSC).bin */
  0x9db0c4b8,  /* Qb (2.06) (PAL).bin */
  0x5e9c5a47,  /* Qb (2.06) (Stella).bin */
  0x82ea5fa6,  /* Qb (Retroactive) (0.01).bin */
  0xe588d6c2,  /* Qb (Retroactive) (0.03).bin */
  0xf6593897,  /* Qb (Retroactive) (0.04).bin */
  0x9c532304,  /* Qb (Retroactive) (0.05) (Mac).bin */
  0x822aa525,  /* Qb (Retroactive) (0.05).bin */
  0x13e60c27,  /* Qb (Retroactive) (0.06).bin */
  0xa441b48c,  /* Qb (Retroactive) (0.10) (PAL).bin */
  0x32474fc2,  /* Qb (Retroactive) (0.10) (Stella-compatable).bin */
  0x90df91ba,  /* Qb (Retroactive) (0.10).bin */
  0xa55c961a,  /* Qb (Retroactive) (0.11) (PAL).bin */
  0x8b4d5fb5,  /* Qb (Retroactive) (0.11) (Stella-compatable).bin */
  0x6be22241,  /* Qb (Retroactive) (0.11).bin */
  0xa249f484,  /* Qb (Retroactive) (0.12) (PAL).bin */
  0x39ab5cc5,  /* Qb (Retroactive) (0.12) (Stella-compatable).bin */
  0xd9042131,  /* Qb (Retroactive) (0.12).bin */
  0xe6c3f47e,  /* Qb (Retroactive) (1.00) (PAL).bin */
  0x2b73f9b8,  /* Qb (Retroactive) (1.00) (Stella-compatable).bin */
  0x8b741fd8,  /* Qb (Retroactive) (1.00).bin */
  0x9cf0383c,  /* Qb (Retroactive) (1.01).bin */
  0xb65b8bf4,  /* Qb (Retroactive) (2.00) (PAL).bin */
  0xacf40dde,  /* Qb (Retroactive) (2.00) (Stella-compatable).bin */
  0xacd68f7e,  /* Qb (Retroactive) (2.00).bin */
  0xe8ec3517,  /* Qb (Retroactive) (2.03) (PAL).bin */
  0x3eba7b70,  /* Qb (Retroactive) (2.03).bin */
  0x88c4edd4,  /* Qb (Retroactive) (2.04) (PAL).bin */
  0xd067a5c4,  /* Qb (Retroactive) (2.04) (Stella-compatable).bin */
  0xa8678746,  /* Qb (Retroactive) (2.04).bin */
  0xa46a791e,  /* Qb (Retroactive) (2.05) (PAL).bin */
  0xea3b44dd,  /* Qb (Retroactive) (2.05).bin */
  0xb1f4996f,  /* Qb (Retroactive) (2.07) (PAL).bin */
  0x56c8f1f4,  /* Qb (Retroactive) (2.07) (Stella-compatable).bin */
  0x2ec8d376,  /* Qb (Retroactive) (2.07).bin */
  0x3b66a5d8,  /* Qb (Retroactive) (2.08) (PAL).bin */
  0xcbc281ad,  /* Qb (Retroactive) (2.08) (Stella-compatable).bin */
  0x0bc0a124,  /* Qb (Retroactive) (2.08) (Test Jump).bin */
  0xb3c2a32f,  /* Qb (Retroactive) (2.08).bin */
  0x3b49bf6d,  /* Qb (Retroactive) (2.09) (PAL).bin */
  0xdffbcef9,  /* Qb (Retroactive) (2.09) (Stella-compatable).bin */
  0x7ffc2899,  /* Qb (Retroactive) (2.09).bin */
  0x6565e911,  /* Qb (Retroactive) (2.11) (PAL).bin */
  0x823d2ad7,  /* Qb (Retroactive) (2.11) (Stella-compatable).bin */
  0xaa9d2d31,  /* Qb (Retroactive) (2.11).bin */
  0x3c31804e,  /* Qb (Retroactive) (2.12) (PAL).bin */
  0xde207fa7,  /* Qb (Retroactive) (2.12) (Stella-compatable).bin */
  0xde399e5f,  /* Qb (Retroactive) (2.12).bin */
  0x6237167e,  /* Qb (Retroactive) (2.14) (PAL).bin */
  0xf96b252f,  /* Qb (Retroactive) (2.14) (Stella-compatable).bin */
  0xf3e3a72f,  /* Qb (Retroactive) (2.14).bin */
  0x220f406f,  /* Qb (Retroactive) (2.15) (PAL).bin */
  0x2990c903,  /* Qb (Retroactive) (2.15) (Stella-compatable).bin */
  0x23184b03,  /* Qb (Retroactive) (2.15).bin */
  0x488e502f,  /* Qb (Retroactive) (Release Candidate #1) (PAL).bin */
  0x26923d92,  /* Qb (Retroactive) (Release Candidate #1) (Stella-Compatable).bin */
  0x26b0bf32,  /* Qb (Retroactive) (Release Candidate #1).bin */
  0xc477158f,  /* Racquetball (1981) (Apollo) [!].bin */
  0x549a1b6b,  /* Star Wars - The Arcade Game (1983) (Parker Bros) (PAL) [!].bin */
  0xed66b6d6,  /* Stell-A-Sketch (PD) [a1].bin */
  0xf1a0a2bd,  /* Synthcart (Paul Slocum).bin */
  0xcb368b0a,  /* Tac Scan (1982) (Sega) (PAL) [p1][!].bin */
  0x1448e3d2,  /* Tape Worm (1982) (Spectravideo).bin */
  0x9b7b16bd,  /* Teller-Jonglieren! (AKA Tanzende Teller) (Starsoft) (PAL) [!].bin */
  0x99066a16,  /* Testcart (Paul Slocum).bin */
  0x8b737fb8,  /* Venture 2 (Tim Snider).bin */
  0x6dd6cda9,  /* Yahtzee (Hozer Video Games).bin */
  0xd2dd0149,  /* Yar Vs. Yar (Justin J. Scott).bin */
  0x84e16d50,  /* Yars' Defeat (Justin J. Scott).bin */
  0xf78c1ef6,  /* birabira.bin */
  0xbef9acef,  /* Burning Desire (Mystique).bin */
  0x7e908404,  /* Midnight Magic (1984) (Atari) (PAL) [!].bin */
  0x286422ce,  /* Midnight Magic (1984) (Atari).bin */
  0xfd0d0551,  /* CatTrax (fixed).bin (UA) */
  0x2c19c728,  /* FunkyFish.bin (UA) */
  0xbc5527e7,  /* Pleiades (fixed).bin (UA) */
  -1
};


/*
 * $Log: ct.c,v $
 * Revision 1.2  2004/05/08 18:06:57  urchlay
 *
 * Added Log tag to all C and asm source files.
 *
 */
